### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by RobTS** [deepstreamIO/deepstream.io-docker#1]
Hi there,

when I try to run the container with docker or docker-compose, I receive the following error and the container closes:

```
deepstream_1  | Error: Cannot find module '/etc/lib/deepstream.io-logger-winston'
deepstreamsample_deepstream_1 exited with code 1
```

**Comment by PhillippOhlandt** [comment]
We resolved it in slack. @RobTS used a wrong `libDir` path in his own config file. It needs to be set to `/var/lib/deepstream`.

**Comment by vovayartsev** [comment]
I faced a similar issue when launching it via Docker (image version 3.0.0) with the following config:
```
plugins:
  storage:
    name: rethinkdb
    options:
      host: db
      port: 28015
      authKey: XXXXXXX
      database: XXXXXXX
      defaultTable: deepstream
      splitChar: '/'
```

I resolved the issue for myself by using my own Dockerfile:
```
FROM deepstreamio/deepstream.io:3.0.0
CMD ["/usr/bin/deepstream", "start", "--lib-dir", "/var/lib/deepstream"]
```
